import React, { useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { X, Image as ImageIcon, Download, Settings, Loader2, FileText, Calendar, BarChart2, Star, Clock, Trash2 } from 'lucide-react';
import { toPng } from 'html-to-image';
import Markdown from 'react-markdown';
import { AppIcon } from './icons/AppIcon';
import { cn } from '../lib/utils';
import { ShareConfig } from './Stats';
import { MOOD_OPTIONS } from '../constants';
import { DatePicker } from './DatePicker';
import { ImageDB } from '../lib/idb';

const getWatermarkHTML = (color: string = 'currentColor') => `
  <div style="width: 100%; height: 1px; background-color: ${color}; margin-bottom: 16px; opacity: 0.15;"></div>
  <div style="display: flex; align-items: center; justify-content: center; gap: 8px;">
    <svg width="14" height="14" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg" style="color: ${color};">
      <g transform="translate(0, -1) scale(1.2)">
        <path d="M 5 146.25 C 20 146.25 40 145.5 52 144 C 58 143.2 64 143.2 64 146.25 C 64 149.3 58 149.3 52 148.5 C 40 147 20 146.25 5 146.25 Z" fill="currentColor"/>
        <g transform="rotate(30, 60, 145)">
          <mask id="sword-mask-watermark">
            <rect x="-100" y="-100" width="400" height="400" fill="white" />
            <circle cx="60" cy="60" r="6" fill="black"/>
            <rect x="58.75" y="63" width="2.5" height="80" fill="black"/>
          </mask>
          <g mask="url(#sword-mask-watermark)">
            <path d="M60 145Q57 125 48 105L50 42L60 18L70 42L72 105Q63 125 60 145Z" fill="currentColor"/>
            <rect x="30" y="36" width="60" height="6" rx="1" fill="currentColor"/>
            <circle cx="30" cy="39" r="5" fill="currentColor"/>
            <circle cx="90" cy="39" r="5" fill="currentColor"/>
            <rect x="55" y="15" width="10" height="21" fill="currentColor"/>
            <circle cx="60" cy="12" r="7" fill="currentColor"/>
          </g>
        </g>
      </g>
    </svg>
    <span>Generated by Scholar's Dungeon</span>
    <span style="opacity: 0.4; margin: 0 4px;">|</span>
    <span style="opacity: 0.9;">https://scholars-dungeon.karakan.top/</span>
  </div>
`;

interface ShareRecordModalProps {
  onClose: () => void;
  containerRef: React.RefObject<HTMLDivElement>;
  config: ShareConfig;
  setConfig: React.Dispatch<React.SetStateAction<ShareConfig>>;
  dailyLogs?: Record<string, any>;
  indicators?: Record<string, { highlight?: boolean; star?: boolean }>;
}

export const ShareRecordModal: React.FC<ShareRecordModalProps> = ({ onClose, containerRef, config, setConfig, dailyLogs = {}, indicators }) => {
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [previewUrls, setPreviewUrls] = React.useState<string[]>([]);
  
  const [exportMode, setExportMode] = React.useState<'statistics' | 'diary' | 'history'>(() => {
    try {
      const saved = localStorage.getItem('scholar_dungeon_share_export_mode');
      if (saved === 'statistics' || saved === 'diary' || saved === 'history') return saved;
    } catch(e){}
    return 'statistics';
  });
  const [exportHistory, setExportHistory] = React.useState<any[]>([]);
  
  useEffect(() => {
    localStorage.setItem('scholar_dungeon_share_export_mode', exportMode);
    if (exportMode === 'history') {
      ImageDB.getAllImages().then((data) => {
        const sorted = data.sort((a,b) => b.timestamp - a.timestamp);
        setExportHistory(sorted);
        setPreviewUrls(sorted.length > 0 ? [sorted[0].url] : []);
      });
    }
  }, [exportMode]);
  const [diaryConfig, setDiaryConfig] = React.useState(() => {
    try {
       const saved = localStorage.getItem('scholar_dungeon_share_diary_config');
       if (saved) return JSON.parse(saved);
    } catch(e){}
    return {
      layout: 'continuous',
      aspectRatio: 'auto',
      fontSize: 'prose-sm',
      fontFamily: 'font-sans',
      removeNewlines: false,
      indentParagraphs: false
    };
  });
  
  useEffect(() => {
    localStorage.setItem('scholar_dungeon_share_diary_config', JSON.stringify(diaryConfig));
  }, [diaryConfig]);
  const [diaryStartDate, setDiaryStartDate] = React.useState<string>(() => {
    const d = new Date();
    d.setMonth(d.getMonth() - 1);
    return d.toISOString().slice(0, 10);
  });
  const [diaryEndDate, setDiaryEndDate] = React.useState<string>(() => new Date().toISOString().slice(0, 10));
  const hiddenDiaryRef = useRef<HTMLDivElement>(null);

  const generatePreview = async () => {
    if (!containerRef.current) return;
    setIsGenerating(true);

    const el = containerRef.current;
    
    // Grab theme bg to blend perfectly
    const computedStyles = window.getComputedStyle(document.documentElement);
    let themeBgColor = computedStyles.getPropertyValue('--color-slate-950').trim();
    if (!themeBgColor) {
      themeBgColor = window.getComputedStyle(document.body).backgroundColor;
      if (!themeBgColor || themeBgColor === 'rgba(0, 0, 0, 0)' || themeBgColor === 'transparent') {
        themeBgColor = '#020617'; // default night theme bg
      }
    }

    try {
      const shareBtn = el.querySelector('#stats-header-actions') as HTMLElement;
      const origShareDisplay = shareBtn ? shareBtn.style.display : '';
      if (shareBtn) shareBtn.style.display = 'none';

      let targetWidth = el.offsetWidth;
      let targetHeight = el.offsetHeight;

      const origStyle = el.getAttribute('style') || '';
      const origMaxWidth = el.style.maxWidth;
      el.style.maxWidth = 'none';

      const sectionIds = ['charts-grid', 'routine-tracker-section', 'heatmap-section', 'daily-activity-section', 'weekly-activity-section'];
      const origSectionStyles: Record<string, string> = {};
      
      const filterIdMap = {
        'daily-activity-section': config.showDaily,
        'weekly-activity-section': config.showWeekly,
        'routine-tracker-section': config.showRoutine,
        'heatmap-section': config.showHeatmap,
      };
      
      const origDisplays: Record<string, string> = {};
      Object.entries(filterIdMap).forEach(([id, show]) => {
         const node = el.querySelector(`#${id}`) as HTMLElement;
         if (node) {
            origDisplays[id] = node.style.display;
            if (!show) node.style.display = 'none';
         }
      });

      if (config.aspectRatio !== 'auto') {
        let targetRatio = 1;
        if (config.aspectRatio === '4:3') targetRatio = 4 / 3;
        else if (config.aspectRatio === '16:9') targetRatio = 16 / 9;

        targetWidth = el.offsetWidth;
        targetHeight = el.offsetHeight;
        const currentRatio = targetWidth / targetHeight;
        
        if (currentRatio > targetRatio) {
          targetHeight = Math.ceil(targetWidth / targetRatio);
        } else {
          targetWidth = Math.ceil(targetHeight * targetRatio);
        }

        // Apply new dimensions directly
        el.style.width = `${targetWidth}px`;
        el.style.height = `${targetHeight}px`;

        // Make the container use Flex to distribute space
        el.style.display = 'flex';
        el.style.flexDirection = 'column';

        // Apply flex to inner sections to stretch them
        sectionIds.forEach(id => {
          const sec = el.querySelector(`#${id}`) as HTMLElement;
          if (sec) {
            origSectionStyles[id] = sec.getAttribute('style') || '';
            sec.style.flex = '1';
            sec.style.display = 'flex';
            
            if (id === 'charts-grid') {
              sec.style.flexDirection = (config.showDaily && config.showWeekly) ? 'row' : 'column';
              sec.style.gap = '2rem'; // ensure there's a nice gap between the left/right columns
            } else {
              sec.style.flexDirection = 'column';
            }
          }
        });

        // Stretch chart wrappers
        const chartWrappers = el.querySelectorAll('.h-48, .min-h-\\[192px\\]');
        chartWrappers.forEach((wrapper: any, index: number) => {
           origSectionStyles[`chart-${index}`] = wrapper.getAttribute('style') || '';
           wrapper.style.flex = '1';
           wrapper.style.display = 'flex';
           wrapper.style.flexDirection = 'column';
           wrapper.style.minHeight = '120px';
           wrapper.style.height = 'auto'; // override fixed height classes
        });

        // Wait for Recharts to snap
        await new Promise(r => setTimeout(r, 600));
      }

      // Remove any leaked watermarks
      el.querySelectorAll('#share-watermark').forEach(n => n.remove());

      // Add watermark
      const watermark = document.createElement('div');
      const bodyColor = window.getComputedStyle(document.body).color || '#94a3b8';
      watermark.id = 'share-watermark';
      watermark.innerHTML = getWatermarkHTML(bodyColor);
      watermark.style.textAlign = 'center';
      watermark.style.color = bodyColor;
      watermark.style.fontSize = '12px';
      watermark.style.padding = '16px 0';
      watermark.style.opacity = '0.7';
      watermark.style.fontWeight = '500';
      watermark.style.marginTop = 'auto'; // push to bottom if flex
      watermark.style.width = '100%';
      el.appendChild(watermark);

      // Capture beautifully scaled pristine layout
      const dataUrl = await toPng(el, {
        pixelRatio: 2, // High resolution for crystal clear text
        skipFonts: true, // Speeds up generation considerably
        fontEmbedCSS: '', // Avoid fetching external fonts during rendering
        width: el.offsetWidth,
        height: el.offsetHeight,
        style: {
          transform: 'none',
          backgroundColor: themeBgColor, // Ensure background is filled perfectly
          margin: '0',
          padding: window.getComputedStyle(el).padding // Retain original padding without doubling
        }
      });

      setPreviewUrls([dataUrl]);

      // Cleanup
      watermark.remove();
      if (shareBtn) shareBtn.style.display = origShareDisplay;
      
      Object.entries(filterIdMap).forEach(([id]) => {
         const node = el.querySelector(`#${id}`) as HTMLElement;
         if (node) {
            node.style.display = origDisplays[id];
         }
      });

      if (config.aspectRatio !== 'auto') {
        el.setAttribute('style', origStyle);
        el.style.maxWidth = origMaxWidth;
        
        sectionIds.forEach(id => {
          const sec = el.querySelector(`#${id}`) as HTMLElement;
          if (sec) {
            sec.setAttribute('style', origSectionStyles[id] || '');
          }
        });

        const chartWrappers = el.querySelectorAll('.h-48, .min-h-\\[192px\\]');
        chartWrappers.forEach((wrapper: any, index: number) => {
           wrapper.setAttribute('style', origSectionStyles[`chart-${index}`] || '');
        });

        // Wait for snap back
        await new Promise(r => setTimeout(r, 100));
      }
    } catch (err) {
      console.error('Error generating image:', err);
    } finally {
      const existingWatermark = document.getElementById('share-watermark');
      if (existingWatermark) existingWatermark.remove();
      setIsGenerating(false);
    }
  };

  const processReflection = (text: string) => {
    if (!text) return '';
    const strText = String(text);
    if (diaryConfig.removeNewlines) {
      return strText.replace(/\n+/g, '');
    }
    return strText;
  };

  const renderPaddedDiaryElement = async (el: HTMLElement, themeColor: string) => {
    const origWidth = 800; // Expected base width inside hidden container
    el.style.height = 'auto';
    const origHeight = el.offsetHeight;
    
    let targetWidth = origWidth;
    let targetHeight = origHeight;
    
    if (diaryConfig.aspectRatio !== 'auto') {
      let targetRatio = 1;
      if (diaryConfig.aspectRatio === '4:3') targetRatio = 4 / 3;
      else if (diaryConfig.aspectRatio === '16:9') targetRatio = 16 / 9;
      
      const currentRatio = origWidth / origHeight;
      if (currentRatio > targetRatio) {
         targetHeight = Math.ceil(origWidth / targetRatio);
      } else {
         targetWidth = Math.ceil(origHeight * targetRatio);
      }
    }
    
    // Create wrapper
    const wrapper = document.createElement('div');
    wrapper.className = 'diary-export-wrapper';
    wrapper.style.width = `${targetWidth}px`;
    wrapper.style.height = `${targetHeight}px`;
    wrapper.style.backgroundColor = themeColor;
    wrapper.style.display = 'flex';
    wrapper.style.flexDirection = 'column';
    wrapper.style.boxSizing = 'border-box';
    
    // Centering flex core
    const innerFlex = document.createElement('div');
    innerFlex.style.flex = '1';
    innerFlex.style.display = 'flex';
    innerFlex.style.flexDirection = 'column';
    innerFlex.style.alignItems = 'center';
    innerFlex.style.justifyContent = 'center';
    innerFlex.style.width = '100%';
    
    const clone = el.cloneNode(true) as HTMLElement;
    clone.style.width = `${origWidth}px`;
    clone.style.height = 'auto';
    clone.style.margin = '0 auto';
    // Remove native HTML watermarks from clone since we use shared dom watermarks
    const hiddenWatermark = clone.querySelector('.diary-native-watermark');
    if (hiddenWatermark) hiddenWatermark.remove();
    
    innerFlex.appendChild(clone);
    wrapper.appendChild(innerFlex);
    
    const watermark = document.createElement('div');
    const bodyColor = window.getComputedStyle(document.body).color || '#94a3b8';
    watermark.innerHTML = getWatermarkHTML(bodyColor);
    watermark.style.textAlign = 'center';
    watermark.style.color = bodyColor;
    watermark.style.fontSize = '12px';
    watermark.style.padding = '16px 0';
    watermark.style.opacity = '0.7';
    watermark.style.fontWeight = '500';
    watermark.style.marginTop = 'auto'; 
    watermark.style.width = '100%';
    wrapper.appendChild(watermark);
    
    // Append temporarily inside hidden ref
    hiddenDiaryRef.current?.appendChild(wrapper);
    
    await new Promise(r => setTimeout(r, 100)); // Layout
    const dataUrl = await toPng(wrapper, { pixelRatio: 2, skipFonts: true, fontEmbedCSS: '', style: { backgroundColor: themeColor }});
    
    wrapper.remove();
    return dataUrl;
  };

  const generateDiaryImagePreview = async () => {
    if (!hiddenDiaryRef.current || filteredLogs.length === 0) {
      setPreviewUrls([]);
      return;
    }
    
    // Cleanup any leaked wrappers from previous failed runs
    hiddenDiaryRef.current.querySelectorAll('.diary-export-wrapper').forEach(n => n.remove());

    setIsGenerating(true);
    try {
      await new Promise(r => setTimeout(r, 200)); 
      
      const computedStyles = window.getComputedStyle(document.documentElement);
      let themeBgColor = computedStyles.getPropertyValue('--color-slate-950').trim();
      if (!themeBgColor) {
        themeBgColor = window.getComputedStyle(document.body).backgroundColor;
        if (!themeBgColor || themeBgColor === 'rgba(0, 0, 0, 0)' || themeBgColor === 'transparent') themeBgColor = '#020617';
      }

      const urls: string[] = [];
      if (diaryConfig.layout === 'continuous') {
        const el = hiddenDiaryRef.current.querySelector('#diary-continuous') as HTMLElement;
        if (el) {
          urls.push(await renderPaddedDiaryElement(el, themeBgColor));
        }
      } else {
        const pages = hiddenDiaryRef.current.querySelectorAll('.diary-page-export');
        for (let i = 0; i < pages.length; i++) {
          urls.push(await renderPaddedDiaryElement(pages[i] as HTMLElement, themeBgColor));
        }
      }
      setPreviewUrls(urls);
    } catch (err) {
      console.error('Error generating diary image:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    setPreviewUrls([]);
  }, [config, exportMode, diaryStartDate, diaryEndDate, diaryConfig]);

  const handleDownload = () => {
    if (previewUrls.length === 0) return;
    
    previewUrls.forEach((url, i) => {
      let fileName = '';
      if (exportMode === 'diary') {
        if (previewUrls.length > 1) {
          fileName = `diary-${diaryStartDate}-to-${diaryEndDate}-page${i+1}`;
        } else {
          fileName = `diary-${diaryStartDate}-to-${diaryEndDate}`;
        }
      } else {
        fileName = `scholar-dungeon-record-${new Date().toISOString().slice(0,10)}`;
      }
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `${fileName}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Save to IDB History
      ImageDB.saveImage(Date.now().toString() + i, url, { name: fileName, mode: exportMode });
    });
  };

  const exportMarkdown = () => {
    const sortedDates = Object.keys(dailyLogs).sort((a,b) => b.localeCompare(a));
    const filtered = sortedDates.filter(d => d >= diaryStartDate && d <= diaryEndDate).map(d => ({ date: d, log: dailyLogs[d] })).filter(x => x.log && x.log.reflection);
    
    let md = `# My Diaries (${diaryStartDate} to ${diaryEndDate})\n\n`;
    filtered.forEach(x => {
        md += `## ${x.date}\n`;
        if (x.log.mood) md += `**Mood**: ${x.log.mood} | **Rating**: ${x.log.rating}/5\n\n`;
        md += `${x.log.reflection}\n\n---\n\n`;
    });
    
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `diaries-${diaryStartDate}-to-${diaryEndDate}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const sortedDates = Object.keys(dailyLogs).sort((a,b) => b.localeCompare(a));
  const filteredLogs = sortedDates
    .filter(d => d >= diaryStartDate && d <= diaryEndDate)
    .map(d => ({ date: d, log: dailyLogs[d] }))
    .filter(x => x.log && x.log.reflection);

  return createPortal(
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
      <div 
        className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />
      
      <div className="relative bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col md:flex-row shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        
        {/* Preview Area */}
        <div className="flex-1 bg-slate-950 p-6 flex flex-col items-center min-h-[300px] border-b md:border-b-0 md:border-r border-slate-800 overflow-y-auto max-h-[60vh] md:max-h-full custom-scrollbar">
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center m-auto gap-4 text-slate-400">
              <Loader2 size={32} className="animate-spin text-indigo-500" />
              <p className="font-bold tracking-wider text-sm uppercase">Rendering Preview...</p>
            </div>
          ) : exportMode === 'diary' && filteredLogs.length === 0 ? (
            <div className="flex flex-col items-center justify-center m-auto gap-3 text-slate-500">
              <Calendar size={48} className="opacity-20" />
              <p className="font-bold text-lg">No Diary Entries</p>
              <p className="text-sm">No diary entries found for the selected date range.</p>
            </div>
          ) : previewUrls.length > 0 ? (
            <div className="flex flex-col gap-6 w-full items-center m-auto">
              {previewUrls.map((url, i) => (
                <img 
                  key={i}
                  src={url} 
                  alt={`Preview ${i}`} 
                  className="max-w-full h-auto rounded-lg shadow-lg border border-slate-800 object-contain transition-all"
                />
              ))}
            </div>
          ) : exportMode !== 'history' ? (
            <div className="flex flex-col items-center justify-center m-auto gap-4 text-slate-500">
              <ImageIcon size={48} className="opacity-20" />
              <p className="font-bold text-lg">Preview not generated</p>
              <p className="text-sm text-center mb-2">Adjust your settings, then click the button below to render the preview.</p>
              <button
                onClick={() => exportMode === 'statistics' ? generatePreview() : generateDiaryImagePreview()}
                disabled={isGenerating}
                className="flex items-center justify-center gap-2 py-3 px-8 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold transition-colors"
              >
                <ImageIcon size={18} />
                Generate Preview
              </button>
            </div>
          ) : null}
        </div>

        {/* Controls */}
        <div className="w-full md:w-80 p-6 flex flex-col gap-6 overflow-y-auto bg-slate-900">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-black text-slate-100 uppercase tracking-tight flex items-center justify-between gap-2">
              <ImageIcon className="text-indigo-500" size={24} />
               Export Image 
            </h2>
            <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-xl text-slate-400 hover:text-white transition-colors">
              <X size={20} />
            </button>
          </div>
          
          <div className="flex gap-2 p-1 bg-slate-950 rounded-lg">
            <button
              onClick={() => setExportMode('statistics')}
              className={cn(
                "flex-1 py-1.5 text-xs font-bold uppercase tracking-wider rounded-md transition-colors",
                exportMode === 'statistics' ? "bg-slate-800 text-white" : "text-slate-500 hover:text-slate-300"
              )}
            >
              Statistics
            </button>
            <button
              onClick={() => setExportMode('diary')}
              className={cn(
                "flex-1 py-1.5 text-xs font-bold uppercase tracking-wider rounded-md transition-colors",
                exportMode === 'diary' ? "bg-slate-800 text-white" : "text-slate-500 hover:text-slate-300"
              )}
            >
              Diaries
            </button>
            <button
              onClick={() => setExportMode('history')}
              className={cn(
                "flex-1 py-1.5 text-xs font-bold uppercase tracking-wider rounded-md transition-colors",
                exportMode === 'history' ? "bg-slate-800 text-white" : "text-slate-500 hover:text-slate-300"
              )}
            >
              History
            </button>
          </div>

          <div className="space-y-4">
            {exportMode === 'history' ? (
              <div className="space-y-4">
                {exportHistory.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-10 gap-3 text-slate-500">
                    <Clock size={32} className="opacity-20" />
                    <p className="font-bold">No Export History</p>
                    <p className="text-xs text-center">Your exported images will appear here, stored safely offline.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {exportHistory.map((item) => (
                      <div 
                        key={item.id} 
                        onClick={() => setPreviewUrls([item.url])}
                        className="relative group bg-slate-950 border border-slate-800 rounded-xl overflow-hidden shadow-sm cursor-pointer hover:border-indigo-500/50 transition-colors"
                      >
                        <img src={item.url} alt={item.name} className="w-full h-auto object-cover opacity-90 group-hover:opacity-100 transition-opacity" />
                        <div className="absolute inset-x-0 bottom-0 p-3 bg-gradient-to-t from-black/90 to-transparent">
                           <div className="flex justify-between items-end">
                              <div>
                                <p className="text-white text-xs font-bold truncate max-w-[180px]">{item.name}</p>
                                <p className="text-slate-400 text-[10px]">{new Date(item.timestamp).toLocaleString()}</p>
                              </div>
                              <button 
                                onClick={(e) => {
                                  e.stopPropagation();
                                  ImageDB.deleteImage(item.id).then(() => {
                                    setExportHistory(prev => prev.filter(x => x.id !== item.id));
                                    if (previewUrls.includes(item.url)) setPreviewUrls([]);
                                  });
                                }}
                                className="p-1.5 bg-red-500/10 hover:bg-red-500/20 text-red-400 rounded-lg transition-colors"
                              >
                                <Trash2 size={14} />
                              </button>
                           </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : exportMode === 'statistics' ? (
              <>
                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                    <Settings size={14} /> Components
                  </h3>
                  <div className="space-y-2">
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={config.showDaily} onChange={(e) => setConfig(prev => ({ ...prev, showDaily: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Daily Activity</span>
                    </label>
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={config.showWeekly} onChange={(e) => setConfig(prev => ({ ...prev, showWeekly: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Weekly Summary</span>
                    </label>
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={config.showRoutine} onChange={(e) => setConfig(prev => ({ ...prev, showRoutine: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Routine Tracker</span>
                    </label>
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={config.showHeatmap} onChange={(e) => setConfig(prev => ({ ...prev, showHeatmap: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Study Heatmap</span>
                    </label>
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={config.showReflection} onChange={(e) => setConfig(prev => ({ ...prev, showReflection: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Show Diary</span>
                    </label>
                  </div>
                </div>

                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Image Aspect Ratio</h3>
                  <div className="grid grid-cols-2 gap-2">
                    {(['auto', '16:9', '4:3', '1:1'] as const).map(ratio => (
                      <button
                        key={ratio}
                        onClick={() => setConfig(prev => ({ ...prev, aspectRatio: ratio }))}
                        className={cn(
                          "py-2 px-3 text-xs font-bold uppercase tracking-widest rounded-lg border transition-all",
                          config.aspectRatio === ratio 
                            ? "bg-indigo-600 border-indigo-500 text-white" 
                            : "bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700"
                        )}
                      >
                        {ratio}
                      </button>
                    ))}
                  </div>
                  <p className="text-[10px] text-slate-500 leading-tight mt-2">Note: Fixed ratios will automatically stretch the components and adjust layout to flawlessly fill the requested dimensions for sharing without distorting or padding the output.</p>
                </div>
              </>
            ) : (
              <div className="space-y-6">
                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                    <Calendar size={14} /> Date Range
                  </h3>
                  <div className="space-y-4">
                    <div>
                      <label className="text-xs text-slate-400 mb-1 block">Start Date</label>
                      <DatePicker 
                        value={diaryStartDate}
                        onChange={setDiaryStartDate}
                        indicators={indicators}
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 mb-1 block">End Date</label>
                      <DatePicker 
                        value={diaryEndDate}
                        onChange={setDiaryEndDate}
                        indicators={indicators}
                      />
                    </div>
                  </div>
                </div>

                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Layout & Output</h3>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      onClick={() => setDiaryConfig(prev => ({ ...prev, layout: 'continuous' }))}
                      className={cn(
                        "py-2 px-3 text-xs font-bold uppercase tracking-widest rounded-lg border transition-all",
                        diaryConfig.layout === 'continuous' 
                          ? "bg-indigo-600 border-indigo-500 text-white" 
                          : "bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700"
                      )}
                    >
                      Continuous
                    </button>
                    <button
                      onClick={() => setDiaryConfig(prev => ({ ...prev, layout: 'per-day' }))}
                      className={cn(
                        "py-2 px-3 text-xs font-bold leading-tight uppercase tracking-widest rounded-lg border transition-all",
                        diaryConfig.layout === 'per-day' 
                          ? "bg-indigo-600 border-indigo-500 text-white" 
                          : "bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700"
                      )}
                    >
                      1/Page
                    </button>
                  </div>
                </div>

                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Formatting</h3>
                  <div className="flex flex-col gap-2">
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={diaryConfig.removeNewlines} onChange={(e) => setDiaryConfig(prev => ({ ...prev, removeNewlines: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Remove Newlines</span>
                    </label>
                    <label className="flex items-center gap-3 p-3 bg-slate-900 border border-slate-800 rounded-xl cursor-pointer hover:border-indigo-500/50 transition-colors">
                      <input type="checkbox" checked={diaryConfig.indentParagraphs} onChange={(e) => setDiaryConfig(prev => ({ ...prev, indentParagraphs: e.target.checked }))} className="accent-indigo-500 w-4 h-4 rounded" />
                      <span className="text-sm font-bold text-slate-200">Indent Paragraphs</span>
                    </label>
                  </div>
                </div>
                
                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Image Aspect Ratio</h3>
                  <div className="grid grid-cols-2 gap-2">
                    {(['auto', '16:9', '4:3', '1:1'] as const).map(ratio => (
                      <button
                        key={ratio}
                        onClick={() => setDiaryConfig(prev => ({ ...prev, aspectRatio: ratio }))}
                        className={cn(
                          "py-2 px-3 text-xs font-bold uppercase tracking-widest rounded-lg border transition-all",
                          diaryConfig.aspectRatio === ratio 
                            ? "bg-indigo-600 border-indigo-500 text-white" 
                            : "bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700"
                        )}
                      >
                        {ratio}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-3">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Typography</h3>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: 'prose-sm', label: 'Small' },
                      { id: 'prose-base', label: 'Medium' },
                      { id: 'prose-lg', label: 'Large' }
                    ].map(f => (
                      <button
                        key={f.id}
                        onClick={() => setDiaryConfig(prev => ({ ...prev, fontSize: f.id }))}
                        className={cn(
                          "py-1.5 px-2 text-[10px] font-bold uppercase tracking-wider rounded-lg border transition-all",
                          diaryConfig.fontSize === f.id 
                            ? "bg-slate-800 border-slate-600 text-white" 
                            : "bg-slate-950 border-slate-800 text-slate-500 hover:text-slate-300"
                        )}
                      >
                        {f.label}
                      </button>
                    ))}
                  </div>
                  <div className="grid grid-cols-3 gap-2">
                    {[
                      { id: 'font-sans', label: 'Sans' },
                      { id: 'font-serif', label: 'Serif' },
                      { id: 'font-mono', label: 'Mono' }
                    ].map(f => (
                      <button
                        key={f.id}
                        onClick={() => setDiaryConfig(prev => ({ ...prev, fontFamily: f.id }))}
                        className={cn(
                          "py-1.5 px-2 text-[10px] font-bold uppercase tracking-wider rounded-lg border transition-all",
                          f.id,
                          diaryConfig.fontFamily === f.id 
                            ? "bg-slate-800 border-slate-600 text-white" 
                            : "bg-slate-950 border-slate-800 text-slate-500 hover:text-slate-300"
                        )}
                      >
                        {f.label}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="mt-auto pt-4 space-y-3">
            <button
              onClick={handleDownload}
              disabled={isGenerating || previewUrls.length === 0}
              className="w-full flex items-center justify-center gap-2 py-4 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:hover:bg-indigo-600 text-white rounded-xl font-black uppercase tracking-widest transition-colors"
            >
              <Download size={18} />
              Save Image
            </button>
            {exportMode === 'diary' && (
              <button
                onClick={exportMarkdown}
                disabled={filteredLogs.length === 0}
                className="w-full flex items-center justify-center gap-2 py-3 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 disabled:hover:bg-slate-800 text-white rounded-xl font-bold transition-colors"
              >
                <FileText size={16} />
                Export Markdown
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Hidden Diary HTML for generating image */}
      {exportMode === 'diary' && filteredLogs.length > 0 && (
        <div 
          ref={hiddenDiaryRef}
          style={{
            position: 'absolute',
            top: '-9999px',
            left: '-9999px',
            width: '800px',
          }}
          className="bg-slate-950 text-slate-200"
        >
          {diaryConfig.layout === 'continuous' ? (
            <div id="diary-continuous" className={cn("bg-slate-950 space-y-8 pb-4", diaryConfig.fontFamily)} style={{ width: '800px' }}>
              <div className="flex items-center gap-4 border-b border-slate-800 p-10 pb-6">
                <div className="w-16 h-16 rounded-2xl bg-indigo-500 flex items-center justify-center shadow-lg shadow-indigo-500/20 text-white">
                  <AppIcon size={36} />
                </div>
                <div>
                  <h2 className="text-3xl font-black uppercase tracking-tight text-white mb-1">My Diaries</h2>
                  <p className="text-slate-400 font-medium">
                    {new Date(diaryStartDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} — {new Date(diaryEndDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                  </p>
                </div>
              </div>

              <div className="space-y-8 px-10 min-h-[300px]">
                {filteredLogs.map(item => {
                  const moodOption = MOOD_OPTIONS.find(m => m.id === item.log.mood);
                  const MoodIcon = moodOption?.icon;
                  return (
                  <div key={item.date} className="bg-slate-900 rounded-2xl p-6 border border-slate-800">
                    <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-800 border-dashed">
                      <h3 className="text-xl font-bold text-indigo-400">
                        {new Date(item.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
                      </h3>
                      <div className="flex items-center gap-3">
                        {moodOption && MoodIcon && (
                          <span className={cn("px-3 py-1 flex items-center gap-1.5 rounded-full text-sm font-medium", moodOption.bg, moodOption.color)}>
                            <MoodIcon size={14} />
                            {moodOption.label}
                          </span>
                        )}
                        <span className="flex items-center gap-0.5 px-3 py-1 bg-indigo-500/10 text-amber-400 border border-indigo-500/20 rounded-full text-sm font-bold">
                          {[1, 2, 3, 4, 5].map(star => (
                            <Star key={star} size={14} className={star <= item.log.rating ? "fill-amber-400 text-amber-400" : "fill-transparent text-slate-600/50"} />
                          ))}
                        </span>
                      </div>
                    </div>
                    <div className={cn(
                      "prose max-w-none text-slate-300 prose-p:text-slate-300 prose-headings:text-slate-100 prose-strong:text-slate-200 prose-li:text-slate-300 prose-ul:text-slate-300 marker:text-slate-500", 
                      diaryConfig.fontSize,
                      diaryConfig.indentParagraphs ? "prose-p:indent-8" : ""
                    )}>
                      <Markdown>{processReflection(item.log.reflection)}</Markdown>
                    </div>
                  </div>
                  );
                })}
              </div>
              
              <div className="diary-native-watermark mt-8 pt-8 px-10 flex items-center justify-between text-slate-500 text-sm relative">
                <div className="absolute top-0 left-0 w-full h-[1px] bg-slate-700 opacity-20"></div>
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400">
                    <AppIcon size={14} />
                  </div>
                  <span>Generated by Scholar's Dungeon</span>
                </div>
                <span>https://scholars-dungeon.karakan.top/</span>
              </div>
            </div>
          ) : (
            <div id="diary-pages">
              {filteredLogs.map(item => {
                const moodOption = MOOD_OPTIONS.find(m => m.id === item.log.mood);
                const MoodIcon = moodOption?.icon;
                return (
                <div key={item.date} className={cn("diary-page-export bg-slate-950 space-y-8 pb-4", diaryConfig.fontFamily)} style={{ width: '800px' }}>
                  <div className="flex items-center gap-4 border-b border-slate-800 p-10 pb-6">
                    <div className="w-16 h-16 rounded-2xl bg-indigo-500 flex items-center justify-center shadow-lg shadow-indigo-500/20 text-white">
                      <AppIcon size={36} />
                    </div>
                    <div>
                      <h2 className="text-3xl font-black uppercase tracking-tight text-white mb-1">My Diary</h2>
                      <p className="text-slate-400 font-medium">
                        {new Date(item.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
                      </p>
                    </div>
                  </div>

                  <div className="px-10 min-h-[300px]">
                    <div className="bg-slate-900 rounded-2xl p-6 border border-slate-800">
                      <div className="flex items-center justify-between mb-4 pb-4 border-b border-slate-800 border-dashed">
                         <h3 className="text-xl font-bold text-indigo-400">
                           {new Date(item.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
                         </h3>
                         <div className="flex items-center gap-3">
                           {moodOption && MoodIcon && (
                             <span className={cn("px-3 py-1 flex items-center gap-1.5 rounded-full text-sm font-medium", moodOption.bg, moodOption.color)}>
                               <MoodIcon size={14} />
                               {moodOption.label}
                             </span>
                           )}
                           <span className="flex items-center gap-0.5 px-3 py-1 bg-indigo-500/10 text-amber-400 border border-indigo-500/20 rounded-full text-sm font-bold">
                             {[1, 2, 3, 4, 5].map(star => (
                               <Star key={star} size={14} className={star <= item.log.rating ? "fill-amber-400 text-amber-400" : "fill-transparent text-slate-600/50"} />
                             ))}
                           </span>
                         </div>
                      </div>
                      <div className={cn(
                        "prose max-w-none text-slate-300 prose-p:text-slate-300 prose-headings:text-slate-100 prose-strong:text-slate-200 prose-li:text-slate-300 prose-ul:text-slate-300 marker:text-slate-500", 
                        diaryConfig.fontSize,
                        diaryConfig.indentParagraphs ? "prose-p:indent-8" : ""
                      )}>
                        <Markdown>{processReflection(item.log.reflection)}</Markdown>
                      </div>
                    </div>
                  </div>

                  <div className="diary-native-watermark mt-8 pt-8 px-10 flex items-center justify-between text-slate-500 text-sm relative">
                    <div className="absolute top-0 left-0 w-full h-[1px] bg-slate-700 opacity-20"></div>
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400">
                        <AppIcon size={14} />
                      </div>
                      <span>Generated by Scholar's Dungeon</span>
                    </div>
                    <span>https://scholars-dungeon.karakan.top/</span>
                  </div>
                </div>
              )})}
            </div>
          )}
        </div>
      )}
    </div>,
    document.body
  );
};

